apiVersion: apps/v1
kind: Deployment
metadata:
  name: southeast
  namespace: botsffl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: southeast
  template:
    metadata:
      labels:
        app: southeast
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: southeast
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        imagePullPolicy: Always
        env:
        - name: SOUTHEAST
          valueFrom:
            configMapKeyRef:
              key: SOUTHEAST
              name: botsffl-league-ids
        - name: USER_ID
          valueFrom:
            configMapKeyRef:
              key: USER_ID
              name: botsffl-league-ids
        - name: CONSUMER_KEY
          valueFrom:
            secretKeyRef:
              key: CONSUMER_KEY
              name: ffl-twitter-account
        - name: CONSUMER_SECRET
          valueFrom:
            secretKeyRef:
              key: CONSUMER_SECRET
              name: ffl-twitter-account
        - name: KEY
          valueFrom:
            secretKeyRef:
              key: KEY
              name: ffl-twitter-account
        - name: SECRET
          valueFrom:
            secretKeyRef:
              key: SECRET
              name: ffl-twitter-account
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              key: REDIS_PASS
              name: redis-pass
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              key: REDIS_HOST
              name: redis-pass